In [1]:
import numpy as np
import matplotlib.pyplot as plt

Задание №1 
Решить систему линейных уравнений

In [4]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение

In [18]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, 5], [11, 4, -7]])
B = np.array([[1, 7, 12, 7, 15]])
C = np.concatenate((A,B.T), axis=1)
print("rank A =", np.linalg.matrix_rank(A, 0.0001))
print("rank AB =", np.linalg.matrix_rank(C, 0.0001))
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B, rcond = None)

rank A = 3
rank AB = 4


(array([1.62845302, 0.06991892, 0.5123584 ]),
 array([10.24819073]),
 3,
 array([14.7942454 ,  9.97915683,  4.53285034]))

3. Сколько решений имеет линейная система. Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [21]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

Так как ранг матрицы А и расширенной не совпадают, система не имеет решений, меняем вектор В

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[3, 2, 1]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[1 2 3 3]
 [4 5 6 2]
 [7 8 9 1]]


(2, 2)

ранги совпадают, решение есть

In [23]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([3, 2, 1])
np.linalg.solve(A, B)

array([ 0.33333333, -4.66666667,  4.        ])

4. Вычислите LU-разложение матрицы:
После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [25]:
import scipy 
import scipy.linalg  

In [26]:
A = np.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73] ])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)


[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [27]:
B = np.array([7, 1, 7])
np.linalg.solve(A, B)

array([ 9.15740741, -1.10648148,  0.01851852])

5. Найдите нормальное псевдорешение недоопределенной системы. Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум.
x + 2y – z = 1
8x – 5y + 2z = 12

In [ ]:
def Q(x, y, z):
    return (x**2 + y**2 + z**2)